[phases.setup]
cmds = ["git submodule update --init --recursive"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "npx serve dist -s -l 3000"
